language: python

cache: pip
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

matrix:
  include:
    - python: 3.4
    - python: 3.5
    - python: "nightly"
      env: PRE=--pre
  allow_failures:
    - python : "nightly"

install:
  - hash -r
  - gcc --version
  - g++ --version
  - pip install cython
  - pip install feather-format
  - python setup.py install

script:
  - python -m pytest --cov=awj --cov-report term-missing
