language: python

cache:
  directories:
    - $HOME/.ccache
    - $HOME/.cache/pip

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - ccache

matrix:
  include:
    - python: 3.4
    - python: 3.5
    - python: "nightly"
      env: PRE=--pre
  allow_failures:
    - python : "nightly"

before_install:
  - export PATH=/usr/lib/ccache:$PATH

install:
  - hash -r
  - ccache -s
  - CC=gcc-4.8 CXX=g++-4.8 pip install cython
  - CC=gcc-4.8 CXX=g++-4.8 pip install feather-format pandas
  - pip install pytest pytest-cov
  - python setup.py install

script:
  - python -m pytest --cov=awj --cov-report term-missing
